application:
  name: hellok8s
  hellok8s:
    image: registry.cn-hangzhou.aliyuncs.com/goproject/k8s_project:go-app-v6
    replicas: 3
    message: "Tt works with Helm Values[v2]!"
    database:
      url: "http://DB_ADDRESS_DEFAULT"
      password: "db_password"
  nginx:
    image: nginx
    replicas: 2
